<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="link authorization-link <?= $block->isLoggedIn() ? 'sign-out' : 'sign-in' ?>" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
        <?= /* @noEscape */ $dataPostParam ?>>

        <span class="label <?= $block->isLoggedIn() ? 'sign-out' : 'sign-in' ?>">
            <?= $escaper->escapeHtml($block->getLabel()) ?>
        </span>
        <img class="img <?= $block->isLoggedIn() ? 'sign-out' : 'sign-in' ?>" src="<?php echo $this->getViewFileUrl('images/login.svg'); ?>" alt="login">
    </a>
</li>
